### ISSUE TITLE
Is not able to find ./wget-lua

### ISSUE THREAD

**Issue by luckcolors** [ArchiveTeam/seesaw-kit#95] opened 2016-03-26 13:25 UTC
Hello.
i think this is self explanatory:
Looking for Wget+Lua in ./wget-lua
./wget-lua: [Errno 2] No such file or directory: './wget-lua'
Looking for Wget+Lua in ./wget-lua-warrior
./wget-lua-warrior: [Errno 8] Exec format error
Looking for Wget+Lua in ./wget-lua-local
./wget-lua-local: [Errno 2] No such file or directory: './wget-lua-local'
Looking for Wget+Lua in ../wget-lua
../wget-lua: [Errno 2] No such file or directory: '../wget-lua'
Looking for Wget+Lua in ../../wget-lua
../../wget-lua: [Errno 2] No such file or directory: '../../wget-lua'
Looking for Wget+Lua in /home/warrior/wget-lua
/home/warrior/wget-lua: [Errno 2] No such file or directory: '/home/warrior/wget-lua'
Looking for Wget+Lua in /usr/bin/wget-lua
Found usable Wget+Lua in /usr/bin/wget-lua

**Comment by luckcolors** [comment] 2016-03-26 13:25
So my current fix is to place a symlink in /usr/bin/wget-lua but still this shuld not be required.

**Comment by yipdw** [comment] 2016-03-28 16:47
This bit:

```
 Looking for Wget+Lua in ./wget-lua
./wget-lua: [Errno 2] No such file or directory: './wget-lua'
Looking for Wget+Lua in ./wget-lua-warrior
./wget-lua-warrior: [Errno 8] Exec format error
```

means that the `wget-lua-warrior` executable is not the correct format for your system.

Some projects ship with a `wget-lua-warrior` executable compiled for 32-bit x86 Linux systems; this is because that's the Warrior VM configuration.  (Whether that's an appropriate distribution mechanism is something we can go over in a separate issue.)

However, this doesn't look like a seesaw bug to me; the executable finder is working as designed, and skipping over `wget-lua` executables that cannot be run.

I'm closing this issue, please comment further if there's more to add.

**Comment by luckcolors** [comment] 2016-03-28 18:06
The main problem is that in the folder i had a precompiled wget-lua and it wasn't detected at all  as you see in the log ./wget-lua: [Errno 2] No such file or directory: './wget-lua', and the wget.lua i compiled works on the host architecture.

**Comment by chfoo** [comment] 2016-04-11 03:48
If you have a precompiled wget-lua, are you executing the script in the same directory as wget-lua? Can you provide a `ls -hal` and any other info so we have more details

**Closed** 2017-01-23 16:42 UTC
Labels: bug, question
