### ISSUE TITLE
Error loading pipeline - docker on unraid

### ISSUE THREAD

**Issue by beardedoffender** [ArchiveTeam/seesaw-kit#126] opened 2021-12-17 17:06 UTC
`Debug log
2021-12-17 11:58:31,159 - seesaw.warrior - DEBUG - Update warrior hq.
2021-12-17 11:58:31,159 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-12-17 11:59:03,603 - seesaw.warrior - DEBUG - Select project reddit
2021-12-17 11:59:03,604 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-12-17 11:59:03,604 - seesaw.warrior - DEBUG - Install project reddit
2021-12-17 11:59:03,604 - seesaw.warrior - DEBUG - git clone
2021-12-17 11:59:05,083 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/reddit'...

2021-12-17 11:59:05,084 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/reddit'...

2021-12-17 11:59:05,084 - seesaw.warrior - DEBUG - Result of the install process: True
2021-12-17 11:59:05,085 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-12-17 11:59:05,089 - seesaw.warrior - DEBUG - Cloning version 8a3f8cd
2021-12-17 11:59:05,138 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-8a3f8cd/pipeline.py
2021-12-17 11:59:05,138 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-12-17 11:59:05,139 - seesaw.warrior - DEBUG - Executing pipeline
2021-12-17 11:59:06,121 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-12-17 11:59:06,270 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
2021-12-17 11:59:20,643 - seesaw.warrior - DEBUG - Select project auto
2021-12-17 11:59:20,643 - seesaw.warrior - DEBUG - Update warrior hq.
2021-12-17 11:59:20,644 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-12-17 11:59:21,060 - seesaw.warrior - DEBUG - Select project reddit
2021-12-17 12:04:26,842 - seesaw.warrior - DEBUG - Select project google-drive
2021-12-17 12:04:26,843 - seesaw.warrior - DEBUG - Start selected project google-drive (reinstall=False)
2021-12-17 12:04:26,843 - seesaw.warrior - DEBUG - Install project google-drive
2021-12-17 12:04:26,844 - seesaw.warrior - DEBUG - git clone
2021-12-17 12:04:27,373 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/google-drive'...

2021-12-17 12:04:27,373 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/google-drive'...

2021-12-17 12:04:27,374 - seesaw.warrior - DEBUG - Result of the install process: True
2021-12-17 12:04:27,374 - seesaw.warrior - DEBUG - Clone project google-drive /home/warrior/projects/google-drive
2021-12-17 12:04:27,379 - seesaw.warrior - DEBUG - Cloning version c8b4d6d
2021-12-17 12:04:27,393 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/google-drive-c8b4d6d/pipeline.py
2021-12-17 12:04:27,394 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-12-17 12:04:27,394 - seesaw.warrior - DEBUG - Executing pipeline
2021-12-17 12:04:27,454 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 52, in <module>
Exception: No usable Wget+At found.
2021-12-17 12:04:27,455 - seesaw.warrior - WARNING - Project google-drive did not install correctly and we're ignoring this problem.
2021-12-17 12:04:38,186 - seesaw.warrior - DEBUG - Select project auto
2021-12-17 12:04:38,187 - seesaw.warrior - DEBUG - Update warrior hq.
2021-12-17 12:04:38,187 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-12-17 12:04:38,618 - seesaw.warrior - DEBUG - Select project reddit
2021-12-17 12:04:38,618 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-12-17 12:04:38,619 - seesaw.warrior - DEBUG - Check project has update reddit
2021-12-17 12:04:38,624 - seesaw.warrior - DEBUG - git fetch
2021-12-17 12:04:38,849 - seesaw.warrior - DEBUG - False
2021-12-17 12:04:38,850 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-12-17 12:04:38,854 - seesaw.warrior - DEBUG - Cloning version 8a3f8cd
2021-12-17 12:04:38,854 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-8a3f8cd/pipeline.py
2021-12-17 12:04:38,854 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-12-17 12:04:38,855 - seesaw.warrior - DEBUG - Executing pipeline
2021-12-17 12:04:38,868 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.`

**Comment by JustAnotherArchivist** [comment] 2022-01-10 23:32
Duplicate of #122

**Closed as completed by JustAnotherArchivist** 2022-01-10 23:32 UTC
